# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/siddharth/FIRA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/siddharth/FIRA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/siddharth/FIRA/CMakeFiles /home/siddharth/FIRA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/siddharth/FIRA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fira

# Build rule for target.
fira: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fira
.PHONY : fira

# fast build rule for target.
fira/fast:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/build
.PHONY : fira/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

arena.o: arena.cpp.o
.PHONY : arena.o

# target to build an object file
arena.cpp.o:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/arena.cpp.o
.PHONY : arena.cpp.o

arena.i: arena.cpp.i
.PHONY : arena.i

# target to preprocess a source file
arena.cpp.i:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/arena.cpp.i
.PHONY : arena.cpp.i

arena.s: arena.cpp.s
.PHONY : arena.s

# target to generate assembly for a file
arena.cpp.s:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/arena.cpp.s
.PHONY : arena.cpp.s

ball.o: ball.cpp.o
.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i
.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s
.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/ball.cpp.s
.PHONY : ball.cpp.s

colors.o: colors.cpp.o
.PHONY : colors.o

# target to build an object file
colors.cpp.o:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/colors.cpp.o
.PHONY : colors.cpp.o

colors.i: colors.cpp.i
.PHONY : colors.i

# target to preprocess a source file
colors.cpp.i:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/colors.cpp.i
.PHONY : colors.cpp.i

colors.s: colors.cpp.s
.PHONY : colors.s

# target to generate assembly for a file
colors.cpp.s:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/colors.cpp.s
.PHONY : colors.cpp.s

contours.o: contours.cpp.o
.PHONY : contours.o

# target to build an object file
contours.cpp.o:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/contours.cpp.o
.PHONY : contours.cpp.o

contours.i: contours.cpp.i
.PHONY : contours.i

# target to preprocess a source file
contours.cpp.i:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/contours.cpp.i
.PHONY : contours.cpp.i

contours.s: contours.cpp.s
.PHONY : contours.s

# target to generate assembly for a file
contours.cpp.s:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/contours.cpp.s
.PHONY : contours.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

our_bot.o: our_bot.cpp.o
.PHONY : our_bot.o

# target to build an object file
our_bot.cpp.o:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/our_bot.cpp.o
.PHONY : our_bot.cpp.o

our_bot.i: our_bot.cpp.i
.PHONY : our_bot.i

# target to preprocess a source file
our_bot.cpp.i:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/our_bot.cpp.i
.PHONY : our_bot.cpp.i

our_bot.s: our_bot.cpp.s
.PHONY : our_bot.s

# target to generate assembly for a file
our_bot.cpp.s:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/our_bot.cpp.s
.PHONY : our_bot.cpp.s

wifi.o: wifi.c.o
.PHONY : wifi.o

# target to build an object file
wifi.c.o:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/wifi.c.o
.PHONY : wifi.c.o

wifi.i: wifi.c.i
.PHONY : wifi.i

# target to preprocess a source file
wifi.c.i:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/wifi.c.i
.PHONY : wifi.c.i

wifi.s: wifi.c.s
.PHONY : wifi.s

# target to generate assembly for a file
wifi.c.s:
	$(MAKE) -f CMakeFiles/fira.dir/build.make CMakeFiles/fira.dir/wifi.c.s
.PHONY : wifi.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fira"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... arena.o"
	@echo "... arena.i"
	@echo "... arena.s"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... colors.o"
	@echo "... colors.i"
	@echo "... colors.s"
	@echo "... contours.o"
	@echo "... contours.i"
	@echo "... contours.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... our_bot.o"
	@echo "... our_bot.i"
	@echo "... our_bot.s"
	@echo "... wifi.o"
	@echo "... wifi.i"
	@echo "... wifi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

